### ISSUE TITLE
Kyle Myint Week 3 Review Ticket: Score: 4/5, Graded by Ak P

### ISSUE THREAD

**Issue by kylem314** [kylem314/btbw#11]
## Graded By: Ak Prathipati 

- Team Grading: 2.5/3
  - Notes from crossover team grading are in our ticket, and participated in group discussions
  - Created team repo and can work from it
  - Active ticket is working on a database
  - plans for deployment and hosting, but not deployed yet (-0.5)

- Individual Grading: 1.5/2
  - Includes user input
  -Documentation is well done; excellent logic in code
  - Square root well implemented  (+0.5)
  - Code doesn't work on repl, something is wrong in calling the Calculator function (-1)

**Comment by akprathipati** [comment]
## Final Grade: 4/5
## Graded By: Ak Prathipati 

- Team Grading: 2.5/3
  - Notes from crossover team grading are in our ticket, and participated in group discussions
  - Created team repo and can work from it
  - Active ticket is working on a database
  - plans for deployment and hosting, but not deployed yet (-0.5)

- Individual Grading: 1.5/2
  - Includes user input
  -Documentation is well done; excellent logic in code
  - Square root well implemented  (+0.5)
  - Code doesn't work on repl, something is wrong in calling the Calculator function (-1)
