### ISSUE TITLE
Week 0 Review Ticket - Crossover Grading

### ISSUE THREAD

**Issue by kylem314** [kylem314/btbw#6]
### Scrum Team GitHub pages (2 points)

Project pages
Web Project: Project Description, Ideas, Wires, Success idea
Embed Project: Hardware Idea, Project Description, Success idea
Team Roles described, Project Owner described, Scrum Board started

### Individual GitHub pages (3 points)

Navigates notes and plans for each Tech Talk
Contains Test Prep plans and participation for success on AP exam (required for test takers)
Navigates to Data Structures work, contains code snippets on problems solutions, links to GitHub for Code, Replit for runtime, or alternatives

**Comment by akprathipati** [comment]
Individual GitHub pages (3 points)

Navigates notes and plans for each Tech Talk
Contains Test Prep plans and participation for success on AP exam (required for test takers)
Navigates to Data Structures work, contains code snippets on problems solutions, links to GitHub for Code, Replit for runtime, or alternatives

0.5/1 on Notes: 
- I think the notes can be more detailed and you can explain the items better. 

1/1- Test Prep 
- The test prep looks great, you have great resources
- very well organized. 

1/1- Github code 
- The code looks great, you implemented Mort's code well.
