### ISSUE TITLE
Week 1 Review Ticket - Crossover

### ISSUE THREAD

**Issue by 1855387** [kylem314/btbw#9]
Github Page: https://kylem314.github.io/btbw/
Scrum Board: https://github.com/kylem314/btbw/projects/1

**Comment by jm1021** [comment]
Database with API and permission system.   Permission system on accounts.   The system will teach out to create your own.  Wireframes are started.  UML diagram is created.   Has a permission sample.

"Students Create, but while they are creating they can use Ours". -- make this theme.

Frontend and Backend assignments have been made.

1/1
